-- SELECT * from account_fiscalyear

-- periodos del año 2021
--SELECT * from account_period
--where fiscalyear_id = 5

-- SELECT id, period_id from account_invoice

-- Facturas del año 2021
--select period_id from account_invoice
--where date_invoice > '2020-12-31'


-- Todas las tablas que hay que arreglar
--select period_id from account_bank_statement
--
--select period_id from account_invoice
--
--select period_id from account_journal_period
--
--select period_id from account_move
--
--select period_id from account_entries_report
--
--select period_id from account_invoice_report
--
--select period_id from report_account_type_sales
--
--select period_id from report_account_sales
--
--select period_id from account_treasury_report
-- en esta no hay registros
--select period_id from account_automatic_reconcile
-- en esta no hay registros
--select period_from, period_to from account_chart
-- en esta no hay registros
--select period_from_cmp, period_to_cmp from accounting_report
-- en esta no hay registros
--select period_id from account_fiscalyear_close
-- en esta no hay registros
--select period from account_invoice_refund
-- en esta no hay registros
--select period_from,period_to  from account_common_report
-- en esta no hay registros
--select period_id  from account_tax_chart
-- no existe la tabla (?)
--select period_id from account_followup_stat
--select period_id from account_voucher
-- no existe la tabla (?)
--select period_id from crm_partner_report_assign
-- no existe la tabla (?)
--select period_id from hr_payslip
-- no existe la tabla (?)
--select period_id from l1on_be.vat.declaration
-- aca es siempre null
--select period_id from stock_inventory
